### ISSUE TITLE
Errors when CiviRules is missing

### ISSUE THREAD

**Issue by twomice** [PalanteJon/org.takethestreets.fastactionlinks#1]
Steps to reproduce errors:

1. Use CiviCRM 4.7.18, where CiviRules is **not** installed.
2. Install fastactionlinks. Observe fatal error "API error: API (CiviRuleTrigger, create) does not exist (join the API team and implement it!)"
3. Install CiviRules extension.
4. Disable fastactionlinks. Note that extension is indeed disabled, but observe fatal error "API error: Either class_name or a combination of object_name and op is mandatory".
5. Uninstall fastactionlinks. Observe no errors.

Also try this one:

1. Use CiviCRM 4.7.18, where CiviRules is **not** installed.
2. Install fastactionlinks. Observe fatal error "API error: API (CiviRuleTrigger, create) does not exist (join the API team and implement it!)"
3. Disable fastactionlinks. Observe no errors.
4. Uninstall fastactionlinks. Observe fatal error, "API (CiviRuleTrigger, get) does not exist (join the API team and implement it!)" and observe that fastactionlinks is not actually uninstalled.
5. Observe that it's pretty hard to uninstall fastactionlinks. On a hunch, install CiviRules.
6. Uninstall fastactionlinks. Observe fatal error "Expected one CiviRuleTrigger but found 0" and observe that fastactionlinks is not actually uninstalled.
7. Observe that it's still pretty hard to uninstall fastactionlinks.
 
Suggested solution:
Not sure about this one. But would be nice to avoid fatal errors and especially avoid the situation where it's hard to uninstall the extension.

**Comment by MegaphoneJon** [comment]
Hmm, interesting.  I spent quite a lot of time working on these exact errors - ah, and now that I look, there's a rather foolish error that I just corrected in `CRM_Fastactionlinks_Util::isCivirulesInstalled`.

Thanks for catching that!  Also note that you'll see a notice generated on uninstall of Fast Action Links when CiviRules is installed, but that's generated by CiviRules itself.

**Comment by twomice** [comment]
Cool, thanks!
